### PR TITLE
Adds odd one out rule

### PR DESCRIPTION
**Pull request by Asheboy**
As suggested by @bengourley in https://github.com/clocklimited/TeaGame/issues/7.

### CODE REVIEW

**Comment by balaclark** [comment]
:-1:

**Comment by domharrington** [comment]
:+1:

**Comment by Asheboy** [comment]
@niallobrien Updated

**Comment by benjaminparnell** [comment]
:+1:

**Comment by vaishal** [comment]
:+1:

**Comment by KenanYusuf** [comment]
:+1: if i must

**Comment by Asheboy** [comment]
@KenanYusuf Do you actually want this rule?

**Comment by KenanYusuf** [comment]
@Asheboy I'm impartial :sheep:

**Pull request merged**
