### PR TITLE
Basic knocking rules added

### PR DESCRIPTION
**Pull request by richhastings**

### CODE REVIEW

**Comment by balaclark** [comment]
:-1: too complex to be formalised in the rules

**Comment by KenanYusuf** [comment]
:+1: Bala is a hater

**Comment by Asheboy** [comment]
:+1: I've never liked Bala anyway

**Comment by oliverjohnstone** [comment]
:-1: I like the social side of the Tea Game... speak to humans ppl!

**Comment by balaclark** [comment]
Closing this as it is lacking the required +3 thumbs up, soz @richhastings

**Pull request closed without merging**
