### PR TITLE
Adding rules regarding pulling blank cards

### PR DESCRIPTION
**Pull request by balaclark**

### CODE REVIEW

**Comment by benjaminparnell** [comment]
:+1:

**Comment by Asheboy** [comment]
:+1:

**Comment by domharrington** [comment]
:+1:

**Comment by domharrington** [comment]
@balaclark who is release manager of this repo? I thought it was @Asheboy. Should you be merging in pull requests?

**Comment by Asheboy** [comment]
@domharrington @balaclark I think that anyone can merge in, as long as we have the +3 needed.

**Comment by balaclark** [comment]
We don't want the tea game pull requests to bottleneck ash from his other work...

**Pull request merged**
