### PR TITLE
All exemptions are cleared on the Monday morning of every week.

### PR DESCRIPTION
**Pull request by benjaminparnell**

### CODE REVIEW

**Comment by Asheboy** [comment]
:-1: This discourages games towards the end of the week.

**Comment by dompainter** [comment]
👍  This encourages games towards the end of the week.

**Comment by vaishal** [comment]
👎 I agree with @Asheboy.

**Comment by richhastings** [comment]
👍  This rewards regular tea game players when non-regular players take part (and are exempt)

**Comment by NicholasLancey** [comment]
👍  I agree with @dompainter.

**Comment by richhastings** [comment]
MERGE IT

**Comment by dompainter** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by balaclark** [comment]
👎

**Comment by balaclark** [comment]
👎

**Pull request merged**
