### PR TITLE
adding drinks clause

### PR DESCRIPTION
**Pull request by balaclark**

### CODE REVIEW

**Comment by vaishal** [comment]
:+1:

**Comment by Asheboy** [comment]
I'd like empty glasses/mugs of hot water to be included please.

**Comment by balaclark** [comment]
Hot water added to the list @Asheboy

**Comment by Asheboy** [comment]
:+1:

**Comment by kuba81** [comment]
:+1:

**Comment by balaclark** [comment]
Ceren also says :+1:

**Pull request merged**
