### PR TITLE
Adds image for odd one out rule

### PR DESCRIPTION
**Pull request by richhastings**
- image added

### CODE REVIEW

**Comment by Asheboy** [comment]
:+1: and my bow!

**Comment by bag-man** [comment]
I'd suggest maybe hosting the image elsewhere so the repo is just the README.md?

**Comment by Asheboy** [comment]
We could just shrink the image a bit. I'm sure it would be below 100kb

**Comment by bag-man** [comment]
I meant more for the "clutter" than filesize. Could possibly base64 encode it?

**Comment by balaclark** [comment]
I agree with @bag-man, the image is too big and takes over the readme.

**Comment by Asheboy** [comment]
Maybe we could have it in an examples folder?

**Comment by Asheboy** [comment]
Image url is dead

**Pull request closed without merging**
