### PR TITLE
Updating exemption and dealer rules

### PR DESCRIPTION
**Pull request by Asheboy**
Updates the rules on exemptions and the dealer, to the current rules.

### CODE REVIEW

**Comment by benjaminparnell** [comment]
Provide a description for your pull requests....

**Comment by domharrington** [comment]
Where are the tests?

**Comment by benjaminparnell** [comment]
+1 for tests

**Comment by balaclark** [comment]
:+1: even though tests are lacking, I agree with the concept.

**Comment by Asheboy** [comment]
I still need the +1's for this to be merged. :) @domharrington @benjaminparnell

**Comment by benjaminparnell** [comment]
:+1:

**Comment by domharrington** [comment]
:+1:

**Pull request merged**
