### PR TITLE
Add minimum number of players

### PR DESCRIPTION
**Pull request by jack828**

### CODE REVIEW

**Comment by KenanYusuf** [comment]
It's only fair 👍  💯

**Comment by benjaminparnell** [comment]
:+1:

**Comment by richhastings** [comment]
In a 3 player game, the chances of 2 cards both being the same and lower than the 3rd card are too high 👍

**Comment by balaclark** [comment]
This needs the update Ash mentioned, card pullers != card players due to exceptions. Untill this edit is made 👎

**Comment by vaishal** [comment]
👍

**Comment by jack828** [comment]
@balaclark is right, change made

**Comment by Asheboy** [comment]
:+1:

**Comment by balaclark** [comment]
👍

**Comment by vaishal** [comment]
👍

**Comment by KenanYusuf** [comment]
👍

**Pull request merged**
