### PR TITLE
Tea game tea making time limit proposal

### PR DESCRIPTION
**Pull request by balaclark**

### CODE REVIEW

**Comment by benjaminparnell** [comment]
:+1:

**Comment by Asheboy** [comment]
Does this mean the making process must start within 15 minutes, or tea is delivered? @balaclark

**Comment by balaclark** [comment]
The process must be started, tea making can take longer.

**Comment by domharrington** [comment]
What’s the punishment if not done?

**Comment by balaclark** [comment]
I suggest lost of exemption.

**Comment by Asheboy** [comment]
15 minutes with Bala in the gimp room...

**Comment by domharrington** [comment]
:scream: disagree. Adding punishments will only piss off recurring players and reduce numbers. I'd rather have more participants and wait 15 mins for the tea than lose players.

**Comment by domharrington** [comment]
Make tea ASAP. This goes without saying. Any loss of exemption is only under extenuating or extreme circumstances. :-1:

**Comment by balaclark** [comment]
What if the tea is not made at all or you have to wait an hour? Surely it goes against the objective of the tea game (having a cup of tea)?

**Comment by domharrington** [comment]
Forgetfulness is not illegal :smile:. A gentle nudge by thirsty people should be enough punishment for anyone.

**Comment by Asheboy** [comment]
I agree with Dom, make tea ASAP. Maybe players should declare any possible delays before playing?

**Comment by balaclark** [comment]
Fair enough, I'll step down...

**Pull request closed without merging**
