### PR TITLE
Makes voting rule more clear

### PR DESCRIPTION
**Pull request by Asheboy**

### CODE REVIEW

**Comment by Asheboy** [comment]
This is actually wrong, don't upvote it yet.

**Comment by benjaminparnell** [comment]
:+1: This seems fair

**Comment by dompainter** [comment]
As conveniently timed this change is, it is fair 👍

**Comment by NicholasLancey** [comment]
👍

**Comment by vaishal** [comment]
👍

**Comment by richhastings** [comment]
👍  Agreed

**Comment by balaclark** [comment]
👍

**Pull request merged**
